export const INGREDIENTS = [
"Salt",
"Rock Salt",
"Black Salt",
"Sugar",
"Jaggery",
"Palm Sugar",
"Date Palm Jaggery",
"Honey",
"Water",
"Oil",
"Mustard Oil",
"Coconut Oil",
"Groundnut Oil",
"Sesame Oil",
"Sunflower Oil",
"Ghee",
"Butter",
"Rice",
"Basmati Rice",
"Brown Rice",
"Parboiled Rice",
"Red Rice",
"Black Rice",
"Sticky Rice",
"Wild Rice",
"Joha Rice",
"Govind Bhog Rice",
"Wheat",
"Wheat Flour",
"Refined Flour",
"Semolina",
"Broken Wheat",
"Barley",
"Maize",
"Millet",
"Finger Millet",
"Pearl Millet",
"Sorghum",
"Foxtail Millet",
"Kodo Millet",
"Little Millet",
"Barnyard Millet",
"Toor Dal",
"Moong Dal",
"Masoor Dal",
"Urad Dal",
"Chana Dal",
"Whole Moong",
"Whole Urad",
"Rajma",
"Chickpeas",
"Black Chickpeas",
"White Peas",
"Green Peas",
"Soybeans",
"Black Eyed Peas",
"Horse Gram",
"Moth Beans",
"Field Beans",
"Potato",
"Sweet Potato",
"Purple Sweet Potato",
"Onion",
"Tomato",
"Garlic",
"Ginger",
"Wild Ginger",
"Green Chili",
"Dry Red Chili",
"Bhut Jolokia",
"Guntur Chili",
"Byadgi Chili",
"Capsicum",
"Carrot",
"Beetroot",
"Radish",
"Turnip",
"Cauliflower",
"Cabbage",
"Broccoli",
"Spinach",
"Fenugreek Leaves",
"Mustard Greens",
"Amaranth Leaves",
"Bathua Leaves",
"Chaulai Leaves",
"Gongura Leaves",
"Jute Leaves",
"Malabar Spinach",
"Poi Leaves",
"Dill Leaves",
"Drumstick",
"Drumstick Leaves",
"Pumpkin",
"Bottle Gourd",
"Ridge Gourd",
"Sponge Gourd",
"Snake Gourd",
"Bitter Gourd",
"Ivy Gourd",
"Raw Banana",
"Brinjal",
"Okra",
"Jackfruit",
"Green Papaya",
"Taro Root",
"Colocasia Leaves",
"Elephant Foot Yam",
"Purple Yam",
"Chinese Potato",
"Arrowroot",
"Lotus Stem",
"Lotus Root",
"Bamboo Shoots",
"Coriander Leaves",
"Mint Leaves",
"Curry Leaves",
"Lemongrass",
"Bay Leaf",
"Betel Leaves",
"Celery Leaves",
"Cumin Seeds",
"Black Cumin",
"Coriander Seeds",
"Mustard Seeds",
"Fenugreek Seeds",
"Fennel Seeds",
"Nigella Seeds",
"Carom Seeds",
"Cloves",
"Cardamom",
"Black Cardamom",
"Cinnamon",
"Nutmeg",
"Mace",
"Star Anise",
"Black Pepper",
"White Pepper",
"Long Pepper",
"Cubeb Pepper",
"Stone Flower",
"Ratan Jot",
"Kapok Buds",
"Anardana",
"Turmeric Powder",
"Red Chili Powder",
"Kashmiri Chili Powder",
"Coriander Powder",
"Cumin Powder",
"Black Pepper Powder",
"Garam Masala",
"Sambar Powder",
"Rasam Powder",
"Pav Bhaji Masala",
"Chaat Masala",
"Kitchen King Masala",
"Meat Masala",
"Chicken Masala",
"Fish Masala",
"Biryani Masala",
"Goda Masala",
"Milk",
"Curd",
"Yogurt",
"Buttermilk",
"Paneer",
"Cheese",
"Khoya",
"Malai",
"Condensed Milk",
"Egg",
"Chicken",
"Mutton",
"Goat Meat",
"Pork",
"Buffalo Meat",
"Duck",
"Quail",
"Turkey",
"Rabbit",
"Fish",
"Rohu Fish",
"Katla Fish",
"Hilsa Fish",
"Pomfret",
"Bombay Duck",
"Mackerel",
"Sardine",
"Tuna",
"Anchovy",
"Eel",
"Prawns",
"Crab",
"Clams",
"Mussels",
"Oysters",
"Squid",
"Dry Fish",
"Cashews",
"Almonds",
"Peanuts",
"Pistachios",
"Walnuts",
"Indian Almond",
"Sesame Seeds",
"Poppy Seeds",
"Sunflower Seeds",
"Pumpkin Seeds",
"Watermelon Seeds",
"Flax Seeds",
"Chia Seeds",
"Fox Nuts",
"Coconut",
"Tender Coconut",
"Coconut Milk",
"Coconut Cream",
"Desiccated Coconut",
"Tamarind",
"Kokum",
"Raw Mango",
"Vinegar",
"Baking Soda",
"Baking Powder",
"Yeast",
"Poha",
"Flattened Rice",
"Puffed Rice",
"Roasted Gram",
"Papad",
"Button Mushroom",
"Oyster Mushroom",
"Milky Mushroom",
"Shiitake Mushroom",
"Wild Mushrooms",
"Banana Flower",
"Banana Stem",
"Neem Flowers",
"Pumpkin Flowers",
"Moringa Flowers",
"Mahua Flowers",
"Palash Flowers",
"Amla",
"Bael Fruit",
"Giloy",
"Guduchi Stem",
"Ashwagandha",
"Shatavari",
"Safed Musli",
"Licorice Root",
"Triphala",
"Fermented Rice Water",
"Rice Starter Culture",
"Fermented Bamboo Paste",
"Fermented Fish Paste",
"Fermented Soy Paste",
"Edible Camphor",
"Rose Water",
"Kewra Water",
"Saffron",
"Sal Leaves",
"Banana Leaves",
"Turmeric Leaves",
"Lotus Leaves",
"Areca Leaves",
"Red Ant Eggs",
"Termites",
"Silkworm Pupae",
"Palm Weevil Larvae"
];

export const INGREDIENT_SUGGESTIONS = [
  "Rice",
  "Onion",
  "Potato",
  "Tomato",
  "Garlic",
  "Ginger",
  "Oil",
  "Salt",
  "Egg",
  "Milk",
  "Chicken",
  "Paneer",
];
